### ISSUE TITLE
Current files

### ISSUE THREAD

**Issue by flyingmusicnote** [justanotherrandomcoder3/Sign-Up-System#1]
The current files don't have a .extension to them, they are just files

what coding language is this? it looks like LUA but it doesn't use local variables, and doesn't have 'ends' or 'thens' in the if statements.

**Comment by flyingmusicnote** [comment]
also there are spaces in the file names. and if this is lua, just use LOVE to make a game

**Comment by justanotherrandomcoder3** [comment]
I use vscode to make games

**Comment by justanotherrandomcoder3** [comment]
Also the coding language is python. and i forgot to tell you that im making it on vscode

**Comment by justanotherrandomcoder3** [comment]
Well, I'll just add them to vscode.

**Comment by flyingmusicnote** [comment]
oh ok, well in Python, if statements are supposed to look like this:
if password_input == password:
    print ("Invalid password")

**Comment by flyingmusicnote** [comment]
make sure you have a python extension installed in VSC to actually run your code and view problems
